#' Load Telemetry Data for a Driver
#'
#' This function takes a session object name (from load_race_session()) and a
#' dirver code.
#'
#' @param session_name the name assigned to a session object
#' (generated by load_race_session)
#' @param driver three letter driver code (see load_drivers() for a list)
#' @param fastest_only boolean value whether to pick all laps or only the fastest
#' by the driver in that session.
#' @importFrom magrittr "%>%"
#' @return A dataframe with columns driverId, lap, stop (number), time (of day),
#' and stop duration
#' @export

get_driver_telemetry <- function(session_name, driver, fastest_only = FALSE){
  if(fastest_only){
    tel <- reticulate::py_run_string(glue::glue("tel ={session_name}.laps.pick_driver('{driver}').pick_fastest().get_telemetry().add_distance()",
                                                session_name = session_name,
                                                driver = driver))
  (tel %>% reticulate::py_to_r())$tel %>%
    reticulate::py_to_r() %>%
    tibble::as_tibble()
  }else{
    tel <- reticulate::py_run_string(glue::glue("tel ={session_name}.laps.pick_driver('{driver}').get_telemetry().add_distance()",
                                                session_name = session_name,
                                                driver = driver))
  (tel %>% reticulate::py_to_r())$tel %>%
    reticulate::py_to_r() %>%
    tibble::as_tibble()
  }
}
