#' Plot Fastest Lap
#'
#' Creates a ggplot object that details the fastest lap for a driver in a race.
#' Complete with a gearshift or speed analysis.
#'
#' @param season number from 2018 to current season (defaults to current season).
#' @param race number from 1 to 23 (depending on season selected) and defaults
#' to most recent.
#' @param session the code for the session to load Options are FP1, FP2, FP3,
#' Q, S, and R. Default is "R", which refers to Race.
#' @param driver three letter driver code (see load_drivers() for a list)
#' @param color argument that indicates which variable to plot overtop the
#' circuit
#' @importFrom magrittr "%>%"
#' @return A ggplot object that indicates grand prix, driver, time and selected
#' color variable.
#' @export

plot_fastest <- function(season = 2022, race = 1, session = 'R', driver, color = 'gear'){
  message("If the session has not been loaded yet, this could take a minute\n\n")

  driver_data <- get_driver_telemetry(season, race, session, driver, T)

  driver_id <- load_drivers(season) %>%
    dplyr::filter(code == driver) %>%
    dplyr::pull(driverId)

  lap_time <- load_laps(season, race) %>%
    dplyr::filter(driverId == driver_id) %>%
    dplyr::filter(time_sec == min(.[, 'time_sec'])) %>%
    dplyr::pull(time)

  race <- load_schedule(season) %>%
    dplyr::filter(round == race) %>%
    dplyr::pull(race_name)

  if(color == 'gear'){
    ggplot2::ggplot(driver_data, ggplot2::aes(X, Y, color = as.factor(nGear), group = Time)) +
      ggplot2::geom_path(size = 4, lineend = 'round') +
      ggsci::scale_color_nejm(name = 'Gear') +
      theme_dark_f1()+
      ggplot2::labs(title = race,
                    subtitle = paste0(driver, ' Fastest Lap | ', lap_time),
                     caption = 'Generated by {f1dataR} package'
                    )
  } else if(color == 'speed'){
    ggplot2::ggplot(driver_data, ggplot2::aes(X, Y, color = Speed, group = Time)) +
      ggplot2::geom_path(size = 4, lineend = 'round') +
      ggplot2::scale_color_gradient(low = 'white', high = 'red')+
      ggplot2::theme_gray() +
      ggplot2::theme(
        panel.grid = ggplot2::element_blank(),
        axis.line = ggplot2::element_blank(),
        axis.text = ggplot2::element_blank(),
        axis.title = ggplot2::element_blank(),
        axis.ticks = ggplot2::element_blank(),
        plot.title  = ggplot2::element_text(face = 'bold', size = 17, color = '#cf1b1f'),
        plot.subtitle  = ggplot2::element_text(face = 'bold', size = 14),
        plot.background = ggplot2::element_rect(fill = "grey10"),
        panel.background = ggplot2::element_blank(),
        legend.background = ggplot2::element_blank(),
        legend.key = ggplot2::element_blank(),
        plot.caption = ggplot2::element_text(size = 8, color = 'white'),
        text = ggplot2::element_text(color = 'white')
      ) +
      ggplot2::labs(title = race,
                    subtitle = paste0(driver, ' Fastest Lap | ', lap_time),
                    caption = 'Generated by {f1dataR} package')
  }

}
