#' Plot Fastest Lap
#'
#' Creates a ggplot object that details the fastest lap for a driver in a race.
#' Complete with a gearshift or speed analysis.
#'
#' @param season number from 2018 to current season (defaults to current season).
#' @param race number from 1 to 23 (depending on season selected) and defaults
#' to most recent.
#' @param round number from 1 to 23 (depending on season selected) and defaults
#' to most recent.
#' @param session the code for the session to load Options are FP1, FP2, FP3,
#' Q, S, SS, and R. Default is "R", which refers to Race.
#' @param driver three letter driver code (see load_drivers() for a list)
#' @param color argument that indicates which variable to plot overtop the
#' circuit
#' @importFrom magrittr "%>%"
#' @importFrom rlang .data
#' @return A ggplot object that indicates grand prix, driver, time and selected
#' color variable.
#' @export

plot_fastest <- function(season = 2022, round = 1, session = 'R', driver, color = 'gear', race = lifecycle::deprecated()){
  message("If the session has not been loaded yet, this could take a minute\n\n")
  if (lifecycle::is_present(race)) {
    lifecycle::deprecate_warn("0.4.1", "plot_fastest(race)", "plot_fastest(round)")
    round <- race
  }

  driver_data <- get_driver_telemetry(season, round, session, driver, T)

  driver_id <- load_drivers(season) %>%
    dplyr::filter(.data$code == driver) %>%
    dplyr::pull(.data$driverId)

  lap_time <- load_laps(season, round) %>%
    dplyr::filter(.data$driverId == driver_id) %>%
    dplyr::filter(.data$time_sec == min(.data$time_sec)) %>%
    dplyr::pull(.data$time)

  race_name <- load_schedule(season) %>%
    dplyr::filter(.data$round == round) %>%
    dplyr::pull(.data$race_name)

  if(color == 'gear'){
    ggplot2::ggplot(driver_data, ggplot2::aes(.data$X, .data$Y, color = as.factor(.data$nGear), group = .data$Time)) +
      ggplot2::geom_path(linewidth = 4, lineend = 'round') +
      ggsci::scale_color_nejm(name = 'Gear') +
      theme_dark_f1() +
      ggplot2::labs(title = race_name,
                    subtitle = paste0(driver, ' Fastest Lap | ', lap_time),
                     caption = 'Generated by {f1dataR} package'
                    )
  } else if(color == 'speed'){
    ggplot2::ggplot(driver_data, ggplot2::aes(.data$X, .data$Y, color = .data$Speed, group = .data$Time)) +
      ggplot2::geom_path(linewidth = 4, lineend = 'round') +
      ggplot2::scale_color_gradient(low = 'white', high = 'red')+
      theme_dark_f1() +
      ggplot2::labs(title = race_name,
                    subtitle = paste0(driver, ' Fastest Lap | ', lap_time),
                    caption = 'Generated by {f1dataR} package')
  }

}
