# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

name: Style and Doc

jobs:
  document:
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: pr-document

      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |
          python_packages <- c("numpy", "fastf1")

          library(reticulate)
          virtualenv_create("r-reticulate", Sys.which("python"))
          virtualenv_install("r-reticulate", python_packages)

          path_to_python <- virtualenv_python("r-reticulate")
          writeLines(sprintf("RETICULATE_PYTHON=%s", path_to_python),
                     Sys.getenv("GITHUB_ENV"))

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Changes Check
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: commit
        if: steps.verify_diff.outputs.changed == 'true' & github.event_name == 'push'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE
          git commit -m 'GH Actions Document'

      - uses: r-lib/actions/pr-push@v2
        if: steps.verify_diff.outputs.changed == 'true' & github.event_name == 'push'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  style:
    name: style
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: install.packages("styler")
        shell: Rscript {0}

      - name: Style
        run: styler::style_pkg()
        shell: Rscript {0}

      - name: Changes Check
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: commit
        if: steps.verify_diff.outputs.changed == 'true' & github.event_name == 'push'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add \*.R \vignettes\*.Rmd README.Rmd
          git commit -m 'GH Actions Style'

      - uses: r-lib/actions/pr-push@v2
        if: steps.verify_diff.outputs.changed == 'true' & github.event_name == 'push'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
